# Generated by Django 5.2.7 on 2025-11-04 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabricante', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=50)),
                ('estoque_limite', models.IntegerField()),
                ('altura', models.FloatField()),
                ('comprimento', models.FloatField()),
                ('largura', models.FloatField()),
                ('peso', models.FloatField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto/')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('fornecedor', models.CharField(max_length=80)),
                ('lote', models.CharField(max_length=80)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_entrando', to='produto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('lote', models.CharField(max_length=80)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_saindo', to='produto.produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
